const jwt = require('jsonwebtoken');
const { success, error } = require('./utils/response');

const JWT_SECRET = process.env.JWT_SECRET || 'birthday-surprise-secret-key-12345';
const GEMINI_API_KEY = process.env.GEMINI_API_KEY;

// Rules-based static generator templates for instant offline fallbacks
const fallbackTemplates = {
    wishes: {
        girlfriend: "Happy Birthday to the one who makes my heart beat faster and my world so much brighter! I love you more every single day. 💕",
        friend: "Happy Birthday buddy! Thanks for always having my back. May this year bring you all the success and happiness you deserve! 🍻",
        sister: "To the best sister in the universe! Thanks for all the sweet childhood memories and for always being my closest support. Have an amazing day! 🎂"
    },
    poems: {
        girlfriend: "A year older, a year more sweet,\nWith you, my life is completely complete.\nYour smile is a flame, your eyes are a star,\nI love you exactly for who you are.\nHappy Birthday, my sweet queen! 💖",
        friend: "Through laughs and sighs, we've walked the mile,\nAnother year to share a smile.\nHappy Birthday to a friend so true,\nHere's to another great year for you! 🌟"
    },
    quotes: {
        other: "“Count your life by smiles, not tears. Count your age by friends, not years.” — John Lennon. Happy Birthday! 💫"
    },
    funny: {
        friend: "Happy Birthday! You’re not getting older... you're just getting closer to those senior citizen discounts! Enjoy your day! 😂"
    },
    romantic: {
        girlfriend: "To my beautiful queen on her birthday: You are my heart, my soul, my today and all of my tomorrows. Wishing you a day as gorgeous as your smile. 😘❤️"
    },
    professional: {
        other: "Wishing you a very Happy Birthday! May this year bring you new professional breakthroughs, exciting opportunities, and great success in all your projects."
    },
    caption: {
        other: "Another orbit around the sun completed! ☀️ Leveling up today. 🎂🎉 #birthdayvibes #levelingup"
    },
    status: {
        other: "It's someone special's birthday today! Send them your warmest love. 🥳🎈✨"
    },
    speech: {
        other: "Ladies and gentlemen, we are gathered here today to celebrate a truly outstanding individual. Over the years, they have brought so much light, laughter, and wisdom into our lives. Let's raise a glass and toast to health, joy, and many more happy years. Happy Birthday!"
    },
    invitation: {
        other: "You're invited to celebrate the birthday bash! Save the date: we're hosting a night of cake, drinks, and unforgettable memories. See you there!"
    },
    hashtags: {
        other: "#HappyBirthday #Celebration #BirthdayVibes #PartyTime #Blessed"
    }
};

module.exports = async function handler(req, res) {
    if (req.method !== 'POST') {
        return error(res, 'Method not allowed', 405);
    }

    // Authenticate creator token
    const authHeader = req.headers.authorization;
    if (!authHeader || !authHeader.startsWith('Bearer ')) {
        return error(res, 'Unauthenticated. Token missing.', 401);
    }

    const token = authHeader.split(' ')[1];
    try {
        jwt.verify(token, JWT_SECRET);
    } catch (e) {
        return error(res, 'Invalid session token.', 401);
    }

    const { recipientName, relation, category } = req.body;

    if (!recipientName || !relation || !category) {
        return error(res, 'Missing generation inputs.', 400);
    }

    // ====================================================
    // GEMINI REST API INTEGRATION
    // ====================================================
    if (GEMINI_API_KEY) {
        try {
            const prompt = `Generate a creative, high-quality, premium ${category.replace('_', ' ')} for my ${relation} whose name is "${recipientName}". Format the output as clean, direct, ready-to-copy text. Do not include any intros, meta-descriptions, labels, quotes, or prefaces. Just generate the exact text.`;

            const response = await fetch(`https://generativelanguage.googleapis.com/v1beta/models/gemini-pro:generateContent?key=${GEMINI_API_KEY}`, {
                method: 'POST',
                headers: { 'Content-Type': 'application/json' },
                body: JSON.stringify({
                    contents: [
                        { parts: [{ text: prompt }] }
                    ]
                })
            });

            const data = await response.json();
            
            if (data.candidates && data.candidates[0] && data.candidates[0].content && data.candidates[0].content.parts[0]) {
                const aiResult = data.candidates[0].content.parts[0].text.trim();
                return success(res, { text: aiResult }, 'Wishes generated by Gemini AI.', 200);
            } else {
                console.error("Gemini structure error:", JSON.stringify(data));
            }
        } catch (err) {
            console.error('Gemini API fetch error:', err);
        }
    }

    // ====================================================
    // RULES ENGINE FALLBACK (If key missing or fetch failed)
    // ====================================================
    const categoryDict = fallbackTemplates[category] || fallbackTemplates['wishes'];
    let textResult = categoryDict[relation] || categoryDict['other'] || fallbackTemplates['wishes']['friend'];
    
    // Replace placeholder name if applicable
    textResult = textResult.replace(/recipient/g, recipientName);

    return success(res, { text: textResult, isFallback: true }, 'Wishes loaded from curated template library.', 200);
};
